embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"block_narrow\"\n"
  "material: \"/lights/materials/light_occluder_sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/example/asset/images.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 200.0\n"
  "friction: 0.1\n"
  "restitution: 0.9\n"
  "group: \"block\"\n"
  "mask: \"block\"\n"
  "mask: \"ball\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 15.0\n"
  "  data: 65.0\n"
  "  data: 10.0\n"
  "}\n"
  "linear_damping: 0.7\n"
  "angular_damping: 0.7\n"
  ""
}
